# Generated by Django 4.2.3 on 2023-07-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_stockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='brand',
            field=models.CharField(default='brand', max_length=200),
        ),
    ]
