# Generated by Django 4.2.3 on 2023-07-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_stockitem_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='price',
            field=models.CharField(default='price', max_length=200),
        ),
    ]
